/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Tools {
  version: number;
  tools: {
    type: string;
    name: string;
    loc?: null | {
      x: number;
      y: number;
    };
    inputs?: {
      [k: string]:
        | string
        | boolean
        | number
        | string[]
        | boolean[]
        | number[]
        | {
            type: string;
            data: number[];
          };
    };
    connections?: {
      [k: string]: string[];
    };
  }[];
  watches?: string[][];
  viewport?: {
    x: number;
    y: number;
    scale: number;
  };
  lockAutoLayout?: boolean;
}
