/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Tools {
  version: number;
  tools: {
    type: string;
    name: string;
    loc: {
      x: number;
      y: number;
    };
    inputs?: {
      [k: string]: string | boolean | number;
    };
    connections?: {
      [k: string]: string[];
    };
  }[];
}

// The above was generated by: json2ts -i src/tools.schema -o src/tools.schema.d.ts
// I added the following by hand. Come at me, json-schema-to-typescript
declare var obj: {};
export default obj;
